networks:
  net:
    driver: bridge
services:
  postgres:
    image: ankane/pgvector:latest
    environment:
      - POSTGRES_DB=ebanking
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - net

volumes:
  postgres-data:
    driver: local